<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Xnotif
 */
?>
<?php
/** @var Amasty\Xnotif\Block\Adminhtml\Analytics\Wanted\ProductList $block */
?>
<div class="amxnotif-2column">
    <p class="amxnotif-title"><?= $block->escapeHtml(__('Most Wanted Products')); ?></p>

    <table class="amxnotif-table">
        <thead class="amxnotif-thead">
        <tr>
            <th class="amxnotif-cell"><?= $block->escapeHtml(__('SKU')); ?></th>
            <th class="amxnotif-cell"><?= $block->escapeHtml(__('Product Name')); ?></th>
            <th class="amxnotif-cell"><?= $block->escapeHtml(__('Qty')); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getWantedProducts() as $product) : ?>
            <tr class="amxnotif-row">
                <td class="amxnotif-cell"><?= $block->escapeHtml($product->getProductSku()); ?></td>
                <td class="amxnotif-cell"><?= $block->escapeHtml($product->getProductName()); ?></td>
                <td class="amxnotif-cell"><?= $block->escapeHtml($product->getWantedCount()); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <a href="<?= $block->escapeUrl($block->getMoreUrl()) ?>"
       class="amxnotif-more-link"
       title="<?= $block->escapeHtml(__("View more")); ?>"
       target="_blank"><?= $block->escapeHtml(__("View more")); ?></a>
</div>
